name: bimdatabase build
on: [push]
jobs:
  build-arch-debug:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm cargo git python-toml
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/bimdatabase/bimdatabase
      - name: check out repository code
        uses: actions/checkout@v3
      - name: run debug build
        run: cargo build --all-targets
      - name: run debug tests
        run: cargo test
      - name: upload debug binary
        uses: actions/upload-artifact@v3
        with:
          name: bimdatabase-debug
          path: |
            target/debug/bimdatabase
  build-arch-release:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm cargo git python-toml
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/bimdatabase/bimdatabase
      - name: check out repository code
        uses: actions/checkout@v3
      - name: run release build
        run: cargo build --all-targets --release
      - name: run release tests
        run: cargo test --release
      - name: upload release binary
        uses: actions/upload-artifact@v3
        with:
          name: rocketbot-release
          path: |
            target/release/bimdatabase
